name: EvenMoreFish
author: Oheers, Alpho320#9202
version: 1.1.3
main: com.oheers.fish.EvenMoreFish
api-version: 1.16
depend: [Vault]
softdepend: [WorldGuard, PlaceholderAPI, RedProtect, LuckPerms]

commands:
  evenmorefish:
    usage: /<command> [name]
    aliases: [emf, balık, balik]